# Generated by Django 4.2.7 on 2023-11-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_type_alter_staff_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='staff',
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
