# Generated by Django 4.2.7 on 2023-11-13 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_clpc'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='star_rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.CreateModel(
            name='StarRating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('star_1', models.IntegerField(default=0)),
                ('star_2', models.IntegerField(default=0)),
                ('star_3', models.IntegerField(default=0)),
                ('star_4', models.IntegerField(default=0)),
                ('star_5', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
                'ordering': ('product',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(default='default@mail.ru', max_length=100)),
                ('written_at', models.DateTimeField(auto_now_add=True)),
                ('star_rating', models.IntegerField(default=5)),
                ('description', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ('written_at',),
            },
        ),
    ]
