# Generated by Django 4.2.7 on 2023-11-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_cafeteria_alter_starrating_options_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='order',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
