# Generated by Django 4.2.7 on 2023-11-19 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_tabletime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='available',
        ),
        migrations.RemoveField(
            model_name='table',
            name='ordered_until',
        ),
    ]
