# Generated by Django 4.2.7 on 2023-11-24 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_table_available_remove_table_ordered_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStatistics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('morning', models.IntegerField(default='0')),
                ('afternoon', models.IntegerField(default='0')),
                ('evening', models.IntegerField(default='0')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'verbose_name': 'Статистика по продуктам',
                'verbose_name_plural': 'Статистика по продуктам',
            },
        ),
    ]
