# Generated by Django 4.2.7 on 2023-11-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_lunchposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='price_rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='comment',
            name='representability_rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='comment',
            name='taste_rating',
            field=models.IntegerField(default=5),
        ),
    ]
