# Generated by Django 4.2.7 on 2023-11-25 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0016_comment_price_rating_comment_representability_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLunch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='lunchposition',
            options={'verbose_name': 'Позиция ланча', 'verbose_name_plural': 'Позиции ланча'},
        ),
        migrations.CreateModel(
            name='UserLunchItems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lunch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.userlunch')),
            ],
        ),
    ]
