# Generated by Django 4.2.7 on 2023-11-18 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_table_order_to_go'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='to_go',
            new_name='in_cafe',
        ),
    ]
