# Generated by Django 4.2.7 on 2023-11-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_rename_to_go_order_in_cafe'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reserve_time',
            field=models.CharField(default='13:30', max_length=10),
        ),
    ]
